name: Generate Snake Animation

on:
  schedule:
    - cron: "0 20 * * *" # Runs every day at 20:00 UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: nahid56-kingsman
          outputs: dist/snake.svg

      - name: Push Snake Animation to the Output Branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
